# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f36a378988471e7df0f627340ff011df6481892321e2dd9bcca2d8251735f50082f65980887ea4762211ec05c920138bf296738b689d25274a3e2cb12a1fe43

test:
  secret_key_base: 05f2c4b6e69b451f0f90c5d08856c740cae7fde22338e1d2da7051af3b383538c2e9377ce712768b12490ade98726d96f1c67d84bc1c54145ab70584867dd924

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
